# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 17:45
from __future__ import unicode_literals

from django.db import migrations
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_evaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='user',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='result',
            field=games.models.JSONField(blank=True, null=True),
        ),
    ]
