# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20161014_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
