# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 22:39
from __future__ import unicode_literals

from django.db import migrations
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20161014_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='result',
            field=games.models.JSONField(blank=True, null=True),
        ),
    ]
