# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-15 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20161014_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloomReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_answers', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
        migrations.CreateModel(
            name='GamificationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_answers', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='eval_type',
            field=models.CharField(choices=[('BL', 'Bloom'), ('GA', 'Gamification')], default='GA', max_length=3),
        ),
        migrations.AlterOrderWithRespectTo(
            name='gamificationreport',
            order_with_respect_to='game',
        ),
        migrations.AlterOrderWithRespectTo(
            name='bloomreport',
            order_with_respect_to='game',
        ),
    ]
