# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20161015_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='game_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
